// Canonical list of supported Pakistani cities (Title Case for reference).
// City values are stored and compared in lowercase across the app
// (sub-admin city, order shippingAddress.city and ticket.city), so the
// validators use PAKISTAN_CITIES_LC.
export const PAKISTAN_CITIES = [
  'Abbottabad',
  'Bahawalpur',
  'Bahawalnagar',
  'Burewala',
  'Charsadda',
  'Chiniot',
  'Dadu',
  'Dera Ghazi Khan',
  'Faisalabad',
  'Gilgit',
  'Gojra',
  'Gujranwala',
  'Gujrat',
  'Hafizabad',
  'Hyderabad',
  'Islamabad',
  'Jacobabad',
  'Jhang',
  'Jhelum',
  'Kamoke',
  'Karachi',
  'Kasur',
  'Khanewal',
  'Khanpur',
  'Kohat',
  'Lahore',
  'Larkana',
  'Mandi Bahauddin',
  'Mardan',
  'Mingora',
  'Mirpur Khas',
  'Multan',
  'Muridke',
  'Muzaffargarh',
  'Muzaffarabad',
  'Nawabshah',
  'Okara',
  'Peshawar',
  'Quetta',
  'Rahim Yar Khan',
  'Rawalpindi',
  'Sadiqabad',
  'Sahiwal',
  'Sargodha',
  'Sheikhupura',
  'Sialkot',
  'Sukkur',
  'Turbat',
  'Wah Cantonment',
]

// Lowercase canonical forms — used for validation & storage.
export const PAKISTAN_CITIES_LC = PAKISTAN_CITIES.map((c) => c.toLowerCase())
